"""add budgets table

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-06 11:30:42.900188
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=12), nullable=False),
    sa.Column('limit_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category_id', name='uq_budget_household_category')
    )
    op.create_index(op.f('ix_budgets_household_id'), 'budgets', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_household_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
