"""add net worth tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-06 12:29:24.723628
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_items_household_id'), 'net_worth_items', ['household_id'], unique=False)
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('assets_cents', sa.Integer(), nullable=False),
    sa.Column('liabilities_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'as_of', name='uq_networth_snapshot_day')
    )
    op.create_index(op.f('ix_net_worth_snapshots_as_of'), 'net_worth_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_net_worth_snapshots_household_id'), 'net_worth_snapshots', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_net_worth_snapshots_household_id'), table_name='net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_snapshots_as_of'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_items_household_id'), table_name='net_worth_items')
    op.drop_table('net_worth_items')
    # ### end Alembic commands ###
